### ISSUE TITLE
ADD IT

### ISSUE THREAD

**Issue by master7720** [barrulik/PenisESP-v2#1]

**Comment by barrulik** [comment]
Im not done yet

**Comment by barrulik** [comment]
The fov check is hard tho

**Comment by master7720** [comment]
Ah ok my b

**Comment by Gav06** [comment]
fov check is not hard

**Comment by barrulik** [comment]
I couldnt work on it on the last few days, i have ton of tests

**Comment by barrulik** [comment]
ima add the not so efficient version for now

**Comment by barrulik** [comment]
idk why it doesnt work, my angle between 2 vectors code

**Comment by barrulik** [comment]
for now, you guys can use that module, after im done with fov check, i will make it into a fabric mod
